//! The CODEOWNERS governance block (pure text generation, no network).
//!
//! `bastion github codeowners` prints a CODEOWNERS block that assigns the
//! reviewer-policy paths to the given owners, so any PR that touches review policy
//! (the registry, the workflow, or CODEOWNERS itself) requires a human review. See
//! the governance section of `docs/developer-guide/github-adapter.md`.

use crate::config;

/// Render the CODEOWNERS block assigning `owners` to the reviewer-policy paths.
///
/// Covers the reviewer registry directory, the Bastion workflow, and the
/// CODEOWNERS file itself (in both common locations).
#[must_use]
pub fn block(owners: &[String]) -> String {
    let owners = owners.join(" ");
    format!(
        "# Bastion reviewer policy: changes here require human review.\n\
         # Generated by `bastion github codeowners`; commit this into .github/CODEOWNERS (or your CODEOWNERS).\n\
         /{config_dir}/ {owners}\n\
         /.github/workflows/bastion.yml {owners}\n\
         /CODEOWNERS {owners}\n\
         /.github/CODEOWNERS {owners}\n",
        config_dir = config::CONFIG_DIR,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn block_covers_policy_paths() {
        let block = block(&["@acme/platform".into(), "@jess".into()]);
        assert!(block.contains("/bastion/ @acme/platform @jess"));
        assert!(block.contains("/.github/workflows/bastion.yml @acme/platform @jess"));
        assert!(block.contains("/CODEOWNERS @acme/platform @jess"));
        assert!(block.contains("require human review"));
        // No em or en dashes in the generated block.
        assert!(!block.contains('\u{2014}') && !block.contains('\u{2013}'));
    }
}
