//! Loading the reviewer registry from disk.
//!
//! Reviewers are declarative and static, defined in a `.bastion.yaml` (or
//! `.bastion.yml`) file at the repository root, under a `reviewers:` key. Keeping
//! them on disk (not generated by code) is what makes them reviewable and gives a
//! stable trigger set.
//!
//! Locally, reviewers can also come from a user-level `.bastion.yaml` in the
//! platform config directory ([`user_config_dir`]). [`Config::discover_merged`]
//! layers it onto the repository's so a personal reviewer runs even when a repo has
//! not adopted Bastion; CI, which has no user config directory, sees the repository
//! set alone.

use std::path::{Path, PathBuf};

use color_eyre::eyre::{Context, Result, bail, eyre};
use serde::{Deserialize, Serialize};

use crate::reviewer::{Backend, Effort, ModelId, Reviewer};

/// The canonical registry file name at the repository root.
pub const REGISTRY_FILE: &str = ".bastion.yaml";

/// The registry file names discovery accepts, in precedence order. Both the
/// `.yaml` and `.yml` spellings are honored; if both exist in the same directory,
/// `.bastion.yaml` wins.
pub const REGISTRY_FILES: [&str; 2] = [".bastion.yaml", ".bastion.yml"];

/// The deprecated pre-rename registry location (`bastion/reviewers.yaml`),
/// relative to the repository root.
///
/// Discovery still finds it, with the lowest precedence, so existing repositories
/// keep working: a directory's `.bastion.yaml`/`.bastion.yml` wins over this, and a
/// closer ancestor wins over a farther one. When it is the file that resolves,
/// [`Config::discover`] logs a deprecation warning pointing at [`REGISTRY_FILE`].
/// This shim will be removed in a future release.
pub const LEGACY_REGISTRY_RELPATH: &str = "bastion/reviewers.yaml";

/// Environment variable that overrides the user-level config directory (where a
/// personal `.bastion.yaml` lives). Mirrors [`crate::paths::DATA_DIR_ENV`]; used in
/// tests and by anyone who wants their reviewers read from a specific directory.
pub const CONFIG_DIR_ENV: &str = "BASTION_CONFIG_DIR";

/// The scope sentinel prepended to a *repository* reviewer's name when a user-level
/// reviewer of the same name carries a different config, so both survive the merge
/// distinctly (the user's keeps the plain name, the repo's becomes
/// `repo:<name>`). It disambiguates rather than drops, since the two registries are
/// authored independently and a user must be able to run their own reviewer locally
/// regardless of the repo's. A fully identical pair is deduplicated instead, so the
/// sentinel only ever marks a genuine difference. The colon is a display detail; the
/// run store maps it to a portable path component (see [`crate::paths`]).
pub const REPO_SCOPE_PREFIX: &str = "repo:";

/// Resolve the user-level config directory by platform convention, honoring
/// [`CONFIG_DIR_ENV`] when set:
///
/// - Linux: `$XDG_CONFIG_HOME/bastion` (default `~/.config/bastion`)
/// - macOS: `~/Library/Application Support/bastion`
/// - Windows: `%APPDATA%\bastion`
///
/// Returns `None` only when no override is set and no home directory can be
/// determined, in which case there is simply no user-level registry to layer in.
/// This is the platform config dir, a sibling of the data dir [`crate::paths`]
/// resolves for run history.
#[must_use]
pub fn user_config_dir() -> Option<PathBuf> {
    if let Some(over) = std::env::var_os(CONFIG_DIR_ENV).filter(|v| !v.is_empty()) {
        return Some(PathBuf::from(over));
    }
    directories::BaseDirs::new().map(|base| base.config_dir().join("bastion"))
}

/// The parsed reviewer registry.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    /// Registry-wide defaults inherited by every reviewer that does not set the
    /// field itself.
    #[serde(default, skip_serializing_if = "Defaults::is_empty")]
    pub defaults: Defaults,
    /// The reviewers defined for this repository.
    #[serde(default)]
    pub reviewers: Vec<Reviewer>,
}

/// Registry-wide defaults applied to every reviewer at load time.
///
/// A reviewer's own field always wins; these fill the gaps. They sit *above* each
/// backend's built-in default (Opus 4.8 at high effort for Claude Code), so a repo
/// can set a house model and effort in one place without repeating them on every
/// reviewer.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[non_exhaustive]
pub struct Defaults {
    /// Default model for reviewers that do not pin one. Like a reviewer's own
    /// `model`, this is backend-specific: a reviewer that inherits it must pin a
    /// backend (the registry rejects an inherited model under `backend: any`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<ModelId>,
    /// Default reasoning effort for reviewers that do not set one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effort: Option<Effort>,
}

impl Defaults {
    /// Whether no registry-wide default is set (the serialized-form skip guard).
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.model.is_none() && self.effort.is_none()
    }
}

impl Config {
    /// Parse a registry from YAML text, validating reviewer-name uniqueness.
    ///
    /// # Errors
    ///
    /// Returns an error if the YAML is malformed or two reviewers share a name.
    pub fn from_yaml(yaml: &str) -> Result<Self> {
        let mut config: Config =
            serde_yaml_ng::from_str(yaml).wrap_err("reviewer registry is not valid YAML")?;
        config.apply_defaults();
        config.validate()?;
        Ok(config)
    }

    /// Load and parse the registry at `path`.
    ///
    /// # Errors
    ///
    /// Returns an error if the file cannot be read or fails [`Config::from_yaml`].
    pub fn load(path: &Path) -> Result<Self> {
        let yaml = std::fs::read_to_string(path)
            .wrap_err_with(|| format!("reading reviewer registry at {}", path.display()))?;
        Self::from_yaml(&yaml)
            .wrap_err_with(|| format!("parsing reviewer registry at {}", path.display()))
    }

    /// Discover and load the registry by walking up from `start` looking for a
    /// `.bastion.yaml` (or `.bastion.yml`) at each ancestor directory.
    ///
    /// Falls back to the deprecated [`LEGACY_REGISTRY_RELPATH`] location, logging a
    /// deprecation warning when that is what resolves.
    ///
    /// # Errors
    ///
    /// Returns an error if no registry is found in any ancestor directory, or if
    /// the discovered file fails to load.
    pub fn discover(start: &Path) -> Result<Self> {
        Self::discover_located(start).map(|(_, config)| config)
    }

    /// Like [`Config::discover`], but also returns the [`Found`] location the
    /// registry was loaded from. A caller that needs both the parsed config and its
    /// path (to report it, say) takes them from one discovery rather than walking the
    /// tree a second time, so the path it reports cannot disagree with the file it
    /// parsed.
    ///
    /// # Errors
    ///
    /// Returns an error if no registry is found in any ancestor directory, or if
    /// the discovered file fails to load.
    pub fn discover_located(start: &Path) -> Result<(Found, Self)> {
        let found = locate_kind(start)?.ok_or_else(|| {
            eyre!(
                "no reviewer registry found; expected {} (or {}) in this repo or an ancestor",
                REGISTRY_FILES[0],
                REGISTRY_FILES[1],
            )
        })?;
        if found.deprecated {
            tracing::warn!(
                "reviewer registry found at the deprecated path `{}`; rename it to `{}` at the repository root. The old location still works for now but will stop being read in a future release.",
                LEGACY_REGISTRY_RELPATH,
                REGISTRY_FILE,
            );
        }
        let config = Self::load(&found.path)?;
        Ok((found, config))
    }

    /// Discover the merged registry `bastion review` runs: the repository registry
    /// (walked up from `start`) with the user-level registry (in `user_dir`)
    /// layered beneath it, so a reviewer a user keeps in their config dir runs
    /// locally whether or not the repository adopts Bastion in CI.
    ///
    /// `user_dir` is the resolved user config directory ([`user_config_dir`]), or
    /// `None` to skip the user-level layer entirely. Either source may be absent;
    /// only the absence of *both* is an error.
    ///
    /// # Errors
    ///
    /// Returns an error if neither a repository nor a user-level registry is found,
    /// if a candidate path cannot be inspected (a stat error other than not-found),
    /// if a discovered file fails to load, or if the merged set fails validation.
    pub fn discover_merged(start: &Path, user_dir: Option<&Path>) -> Result<Self> {
        Self::discover_merged_located(start, user_dir).map(|(_, config)| config)
    }

    /// Like [`Config::discover_merged`], but also returns the [`Sources`] the merged
    /// config was built from, so a caller (such as `bastion validate`) can report
    /// exactly which files fed it.
    ///
    /// The repository registry is loaded as the base, then the user-level reviewers
    /// are merged onto it as a set: an identical reviewer in both files is
    /// deduplicated, and a same-name-different-config collision keeps both with the
    /// repo side scoped to [`REPO_SCOPE_PREFIX`] (the merge is `layer_user`). The
    /// merged set is re-validated so a residual duplicate name fails closed.
    ///
    /// # Errors
    ///
    /// Returns an error if neither a repository nor a user-level registry is found,
    /// if a candidate path cannot be inspected (a stat error other than not-found,
    /// from [`locate_kind`] or [`locate_user`]), if a discovered file fails to load,
    /// or if the merged set fails validation.
    pub fn discover_merged_located(
        start: &Path,
        user_dir: Option<&Path>,
    ) -> Result<(Sources, Self)> {
        let repo = locate_kind(start)?;
        let user = match user_dir {
            Some(dir) => locate_user(dir)?,
            None => None,
        };

        if repo.is_none() && user.is_none() {
            bail!(
                "no reviewer registry found; expected {} (or {}) in this repo or an ancestor{}",
                REGISTRY_FILES[0],
                REGISTRY_FILES[1],
                user_dir.map_or_else(String::new, |dir| format!(
                    ", or {} in your user config directory ({})",
                    REGISTRY_FILE,
                    dir.display()
                )),
            );
        }

        let mut config = match &repo {
            Some(found) => {
                if found.deprecated {
                    tracing::warn!(
                        "reviewer registry found at the deprecated path `{}`; rename it to `{}` at the repository root. The old location still works for now but will stop being read in a future release.",
                        LEGACY_REGISTRY_RELPATH,
                        REGISTRY_FILE,
                    );
                }
                Self::load(&found.path)?
            }
            None => Config::default(),
        };

        if let Some(path) = &user {
            config.layer_user(Self::load(path)?);
            // The two registries are validated independently; re-validate the merged
            // set so a name that still collides after scoping (a pathological pair)
            // fails closed rather than overwriting a run-store directory.
            config.validate()?;
        }

        Ok((Sources { repo, user }, config))
    }

    /// Fold the registry-wide [`Defaults`] into each reviewer: a reviewer's own
    /// `model`/`effort` wins, and the default fills the gap. Resolving here, once,
    /// means every downstream consumer (and the persisted run record) sees the
    /// effective values rather than re-deriving them, and the `model`-under-`any`
    /// guard in [`Config::validate`] catches an inherited model too.
    fn apply_defaults(&mut self) {
        let Defaults { model, effort } = &self.defaults;
        for reviewer in &mut self.reviewers {
            if reviewer.model.is_none() {
                reviewer.model = model.clone();
            }
            if reviewer.effort.is_none() {
                reviewer.effort = effort.clone();
            }
        }
    }

    /// Layer a user-level registry onto this repository registry, merging the two
    /// reviewer lists into a set.
    ///
    /// Each registry resolves its own [`Defaults`] at parse time (`from_yaml` runs
    /// `apply_defaults` before this is reached), so the reviewers in both lists
    /// already carry their effective `model`/`effort`; layering compares and combines
    /// the effective configs. For each user reviewer, by name against the repo:
    ///
    /// - **No repo reviewer of that name:** the user reviewer is appended.
    /// - **A repo reviewer with an identical config:** the two are the same reviewer,
    ///   so the pair is deduplicated to the single repo copy (the user's is dropped).
    /// - **A repo reviewer with a different config:** a genuine collision of two
    ///   independently authored reviewers. Both are kept; the user's keeps the plain
    ///   name and the repo's is scoped to [`REPO_SCOPE_PREFIX`]`<name>` so the names
    ///   stay unique. Since the repo and user files are governed separately, neither
    ///   silently wins: a local run sees both.
    ///
    /// The combined list is re-validated by the caller, so a scoped name that still
    /// collides (a pathological registry) fails closed rather than overwriting.
    fn layer_user(&mut self, user: Config) {
        use std::collections::BTreeMap;

        // Index the repo (base) reviewers by name to test collisions and equality.
        let repo: BTreeMap<&str, &Reviewer> = self
            .reviewers
            .iter()
            .map(|r| (r.name.as_str(), r))
            .collect();

        let mut append = Vec::new();
        let mut scope = std::collections::BTreeSet::new();
        for reviewer in &user.reviewers {
            match repo.get(reviewer.name.as_str()) {
                // Same name, same config: the identical reviewer defined in both
                // files. Keep the single repo copy; drop the user duplicate.
                Some(existing) if **existing == *reviewer => {}
                // Same name, different config: a real collision. Keep the user
                // reviewer as-is and mark the repo side for scoping below.
                Some(_) => {
                    scope.insert(reviewer.name.clone());
                    append.push(reviewer.clone());
                }
                // Novel reviewer: append it.
                None => append.push(reviewer.clone()),
            }
        }
        drop(repo);

        for reviewer in &mut self.reviewers {
            if scope.contains(&reviewer.name) {
                reviewer.name = format!("{REPO_SCOPE_PREFIX}{}", reviewer.name);
            }
        }
        self.reviewers.extend(append);
    }

    fn validate(&self) -> Result<()> {
        let mut seen = std::collections::BTreeSet::new();
        let mut seen_components = std::collections::BTreeSet::new();
        for reviewer in &self.reviewers {
            if !seen.insert(reviewer.name.as_str()) {
                bail!("duplicate reviewer name: {}", reviewer.name);
            }
            // A reviewer name becomes a directory component in the run store, mapped
            // to a portable form first (`crate::paths`). Two distinct names that map
            // to the same component, or a degenerate one that escapes or names the
            // directory itself, would let one run clobber another's saved transcript
            // and verdict. Catch both here so a name collision fails closed at load
            // rather than silently overwriting at persist time.
            let component = crate::paths::path_component(&reviewer.name);
            if component.is_empty() || component == "." || component == ".." {
                bail!(
                    "reviewer name '{}' is not a usable run-store directory name; \
                     give it a plain name",
                    reviewer.name
                );
            }
            if !seen_components.insert(component.clone()) {
                bail!(
                    "reviewer '{}' collides with another reviewer once names are \
                     reduced to the run-store path component '{component}'; rename one",
                    reviewer.name
                );
            }
            // A model id means something only to the backend it names, so it only
            // makes sense once the backend is pinned. Reject a model under
            // `backend: any` (fail closed at the boundary) rather than letting, say,
            // a Codex id reach Claude Code once `any` resolves. This fires for an
            // inherited default model too, since `apply_defaults` ran first.
            if reviewer.model.is_some() && reviewer.backend == Backend::Any {
                bail!(
                    "reviewer '{}' sets a model but leaves backend: any; a model id is \
                     backend-specific, so pin a backend (claude-code or codex)",
                    reviewer.name
                );
            }
        }
        Ok(())
    }
}

/// A located registry file and whether it came from the deprecated location.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Found {
    /// The resolved path to the registry file.
    pub path: PathBuf,
    /// True when `path` is the deprecated [`LEGACY_REGISTRY_RELPATH`] location.
    pub deprecated: bool,
}

/// The registry sources layered into a merged config: the repository registry
/// (found by walking up from the start directory) and the user-level registry (in
/// the platform config directory). Either may be absent, but a successful
/// [`Config::discover_merged_located`] always has at least one.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Sources {
    /// The repository registry, if one was found in an ancestor directory.
    pub repo: Option<Found>,
    /// The user-level registry, if one was found in the config directory.
    pub user: Option<PathBuf>,
}

/// Locate the registry file by walking up from `start`.
///
/// Returns the path to the first registry found in an ancestor directory, or
/// `None` if none exists up to the filesystem root. Within a single directory the
/// `.bastion.yaml` spelling wins over `.bastion.yml`, and both win over the
/// deprecated `bastion/reviewers.yaml`; a closer ancestor wins over a farther one.
///
/// # Errors
///
/// Propagates a non-`NotFound` stat error, as [`locate_kind`] does.
pub fn locate(start: &Path) -> Result<Option<PathBuf>> {
    Ok(locate_kind(start)?.map(|found| found.path))
}

/// Whether a registry candidate is present at `path`.
///
/// Only a `NotFound` result means "absent"; any other stat error (a permission
/// problem, say) is propagated with path context rather than read as absence, so a
/// registry whose presence cannot be determined fails discovery closed instead of
/// vanishing. A path that exists but is not a loadable file (a directory of that
/// name, say) still counts as present here, so discovery returns it and the
/// subsequent [`Config::load`] fails closed with a clear read error rather than the
/// candidate being silently skipped.
fn registry_present(path: &Path) -> Result<bool> {
    path.try_exists()
        .wrap_err_with(|| format!("checking for a reviewer registry at {}", path.display()))
}

/// Locate a user-level registry inside `dir`, a single directory with no ancestor
/// walk (a user config directory is a flat location, not a tree). Within it the
/// `.bastion.yaml` spelling wins over `.bastion.yml`, the same precedence
/// [`locate_kind`] applies per directory. The deprecated `bastion/reviewers.yaml`
/// shim is repository-only and not honored here.
///
/// # Errors
///
/// Returns an error if a candidate path cannot be inspected for a reason other than
/// not existing (a stat error such as a permission problem). Such an error is
/// propagated rather than read as "no registry", so a user-level gate reviewer is
/// never silently dropped because its registry could not be stat'ed or could not be
/// loaded: discovery fails closed.
pub fn locate_user(dir: &Path) -> Result<Option<PathBuf>> {
    for name in REGISTRY_FILES {
        let candidate = dir.join(name);
        if registry_present(&candidate)? {
            return Ok(Some(candidate));
        }
    }
    Ok(None)
}

/// Like [`locate`], but also reports whether the resolved path is the deprecated
/// location, so callers can warn.
///
/// # Errors
///
/// Returns an error if a candidate path cannot be inspected for a reason other than
/// not existing (a stat error such as a permission problem); it is propagated rather
/// than read as "no registry", so a governed repository gate is never silently
/// skipped because its registry could not be inspected.
pub fn locate_kind(start: &Path) -> Result<Option<Found>> {
    for dir in start.ancestors() {
        for name in REGISTRY_FILES {
            let candidate = dir.join(name);
            if registry_present(&candidate)? {
                return Ok(Some(Found {
                    path: candidate,
                    deprecated: false,
                }));
            }
        }
        let legacy = dir.join(LEGACY_REGISTRY_RELPATH);
        if registry_present(&legacy)? {
            return Ok(Some(Found {
                path: legacy,
                deprecated: true,
            }));
        }
    }
    Ok(None)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_a_two_reviewer_registry() {
        let yaml = r"
reviewers:
  - name: file-responsibility
    trigger: [src/**/*.ts]
    mode: gate
    prompt: Check single responsibility.
  - name: api-compatibility
    trigger: [src/server/**, src/client/**]
    mode: gate
    prompt: Check API compatibility.
";
        let config = Config::from_yaml(yaml).expect("valid registry");
        assert_eq!(config.reviewers.len(), 2);
        assert_eq!(config.reviewers[0].name, "file-responsibility");
    }

    #[test]
    fn rejects_duplicate_reviewer_names() {
        let yaml = r"
reviewers:
  - name: dup
    trigger: [a]
    mode: gate
    prompt: one
  - name: dup
    trigger: [b]
    mode: advisor
    prompt: two
";
        let err = Config::from_yaml(yaml).unwrap_err();
        assert!(err.to_string().contains("duplicate reviewer name"));
    }

    #[test]
    fn registry_defaults_fill_unset_reviewer_fields_and_explicit_values_win() {
        let yaml = r"
defaults:
  model: gpt-5
  effort: high
reviewers:
  - name: inherits
    trigger: [src/**]
    mode: gate
    backend: codex
    prompt: p
  - name: overrides
    trigger: [src/**]
    mode: gate
    backend: codex
    model: gpt-5-codex
    effort: low
    prompt: p
";
        let config = Config::from_yaml(yaml).expect("valid registry");
        let inherits = &config.reviewers[0];
        assert_eq!(inherits.model.as_ref().map(ModelId::as_str), Some("gpt-5"));
        assert_eq!(inherits.effort.as_ref().map(Effort::as_str), Some("high"));
        let overrides = &config.reviewers[1];
        assert_eq!(
            overrides.model.as_ref().map(ModelId::as_str),
            Some("gpt-5-codex")
        );
        assert_eq!(overrides.effort.as_ref().map(Effort::as_str), Some("low"));
    }

    #[test]
    fn a_model_under_backend_any_is_rejected() {
        let yaml = r"
reviewers:
  - name: stray
    trigger: [src/**]
    mode: gate
    model: gpt-5
    prompt: p
";
        let err = Config::from_yaml(yaml).unwrap_err();
        assert!(
            err.to_string().contains("backend: any"),
            "error should explain the model needs a pinned backend, got: {err}"
        );
    }

    #[test]
    fn an_inherited_default_model_under_backend_any_is_also_rejected() {
        // The guard fires after defaults resolve, so a default model folded into a
        // `backend: any` reviewer is caught too.
        let yaml = r"
defaults:
  model: gpt-5
reviewers:
  - name: stray
    trigger: [src/**]
    mode: gate
    prompt: p
";
        let err = Config::from_yaml(yaml).unwrap_err();
        assert!(err.to_string().contains("backend: any"));
    }

    #[test]
    fn rejects_an_unknown_reviewer_field() {
        // A misspelled or stray key is a mistake, not a no-op: `deny_unknown_fields`
        // turns it into a clear load error rather than silently ignoring it.
        let yaml = r"
reviewers:
  - name: typo
    trigger: [src/**]
    mode: gate
    bakend: codex
    prompt: p
";
        let err = Config::from_yaml(yaml).unwrap_err();
        assert!(
            format!("{err:#}").contains("unknown field `bakend`"),
            "error should name the unknown field, got: {err:#}"
        );
    }

    #[test]
    fn rejects_an_unknown_top_level_field() {
        // `reviewer:` instead of `reviewers:` would otherwise parse to an empty
        // registry and silently review nothing; reject it at the boundary.
        let yaml = r"
reviewer:
  - name: oops
    trigger: [src/**]
    mode: gate
    prompt: p
";
        let err = Config::from_yaml(yaml).unwrap_err();
        assert!(
            format!("{err:#}").contains("unknown field `reviewer`"),
            "error should name the unknown top-level field, got: {err:#}"
        );
    }

    #[test]
    fn discovers_registry_in_an_ancestor_directory() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILE),
            "reviewers:\n  - name: r\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let nested = tmp.path().join("src").join("deep");
        std::fs::create_dir_all(&nested).unwrap();

        let config = Config::discover(&nested).expect("found via ancestor walk");
        assert_eq!(config.reviewers.len(), 1);
    }

    #[test]
    fn discovers_the_yml_spelling_too() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILES[1]),
            "reviewers:\n  - name: r\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let config = Config::discover(tmp.path()).expect("found via .yml spelling");
        assert_eq!(config.reviewers.len(), 1);
    }

    #[test]
    fn the_yaml_spelling_wins_when_both_exist() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILES[0]),
            "reviewers:\n  - name: from-yaml\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILES[1]),
            "reviewers:\n  - name: from-yml\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let config = Config::discover(tmp.path()).expect("found, .yaml wins");
        assert_eq!(config.reviewers[0].name, "from-yaml");
    }

    #[test]
    fn discovers_the_deprecated_legacy_location() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join("bastion")).unwrap();
        std::fs::write(
            tmp.path().join(LEGACY_REGISTRY_RELPATH),
            "reviewers:\n  - name: legacy\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        // It resolves and loads.
        let config = Config::discover(tmp.path()).expect("legacy registry still discovered");
        assert_eq!(config.reviewers[0].name, "legacy");

        // ...and it is flagged as deprecated so the caller can warn.
        let found = locate_kind(tmp.path())
            .expect("stat ok")
            .expect("legacy located");
        assert!(found.deprecated, "legacy path must be flagged deprecated");
        assert!(found.path.ends_with("reviewers.yaml"));
    }

    #[test]
    fn the_root_registry_wins_over_the_legacy_location() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILE),
            "reviewers:\n  - name: from-root\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();
        std::fs::create_dir_all(tmp.path().join("bastion")).unwrap();
        std::fs::write(
            tmp.path().join(LEGACY_REGISTRY_RELPATH),
            "reviewers:\n  - name: from-legacy\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let found = locate_kind(tmp.path()).expect("stat ok").expect("located");
        assert!(
            !found.deprecated,
            "the root .bastion.yaml must win over the legacy path"
        );
        let config = Config::discover(tmp.path()).expect("loads the root registry");
        assert_eq!(config.reviewers[0].name, "from-root");
    }

    #[test]
    fn discovery_fails_clearly_when_absent() {
        let tmp = tempfile::tempdir().unwrap();
        let err = Config::discover(tmp.path()).unwrap_err();
        assert!(err.to_string().contains("no reviewer registry found"));
    }

    /// Write `yaml` as a `.bastion.yaml` into a fresh temp dir and return both.
    fn registry_dir(yaml: &str) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(REGISTRY_FILE), yaml).unwrap();
        dir
    }

    #[test]
    fn user_config_dir_honors_the_env_override() {
        let tmp = tempfile::tempdir().unwrap();
        // Safety: single-threaded test; no other thread reads the environment here.
        unsafe { std::env::set_var(CONFIG_DIR_ENV, tmp.path()) };
        assert_eq!(user_config_dir().as_deref(), Some(tmp.path()));
        unsafe { std::env::remove_var(CONFIG_DIR_ENV) };
    }

    #[test]
    fn locate_user_finds_a_flat_registry_and_prefers_yaml() {
        let dir = tempfile::tempdir().unwrap();
        assert!(locate_user(dir.path()).expect("stat ok").is_none());
        std::fs::write(dir.path().join(REGISTRY_FILES[1]), "reviewers: []\n").unwrap();
        std::fs::write(dir.path().join(REGISTRY_FILES[0]), "reviewers: []\n").unwrap();
        assert!(
            locate_user(dir.path())
                .expect("stat ok")
                .expect("located")
                .ends_with(REGISTRY_FILES[0])
        );
    }

    #[test]
    fn validate_rejects_two_names_that_reduce_to_the_same_path_component() {
        // Distinct raw names that sanitize to the same run-store directory must not
        // both persist (one would clobber the other); reject at load. `repo:test` and
        // `repo-test` both reduce to `repo-test`.
        let yaml = "\
reviewers:
  - name: 'repo:test'
    trigger: [x]
    mode: gate
    prompt: p
  - name: repo-test
    trigger: [x]
    mode: gate
    prompt: p
";
        let err = Config::from_yaml(yaml).unwrap_err();
        assert!(
            err.to_string().contains("path component"),
            "expected a path-component collision error, got: {err}"
        );
    }

    #[test]
    fn validate_rejects_a_degenerate_reviewer_name() {
        // A name that reduces to the directory itself (`..`) would escape the run's
        // reviewers directory; reject it rather than write artifacts somewhere
        // surprising.
        let yaml = "reviewers:\n  - name: '..'\n    trigger: [x]\n    mode: gate\n    prompt: p\n";
        let err = Config::from_yaml(yaml).unwrap_err();
        assert!(
            err.to_string().contains("run-store directory name"),
            "got: {err}"
        );
    }

    const REPO_YAML: &str = "\
reviewers:
  - name: tenant-isolation
    trigger: [src/**]
    mode: gate
    prompt: repo prompt
";

    #[test]
    fn merge_appends_a_distinct_user_reviewer() {
        let repo = registry_dir(REPO_YAML);
        let user = registry_dir(
            "reviewers:\n  - name: my-style\n    trigger: [src/**]\n    mode: advisor\n    prompt: p\n",
        );
        let config = Config::discover_merged(repo.path(), Some(user.path())).expect("merges");
        let names: Vec<&str> = config.reviewers.iter().map(|r| r.name.as_str()).collect();
        assert_eq!(names, ["tenant-isolation", "my-style"]);
    }

    #[test]
    fn merge_works_with_only_a_user_registry() {
        // A repo that has not adopted Bastion: discovery from an empty dir finds no
        // repo registry, but the user's reviewers still run.
        let empty = tempfile::tempdir().unwrap();
        let user = registry_dir(
            "reviewers:\n  - name: my-style\n    trigger: [src/**]\n    mode: advisor\n    prompt: p\n",
        );
        let config = Config::discover_merged(empty.path(), Some(user.path())).expect("user only");
        assert_eq!(config.reviewers.len(), 1);
        assert_eq!(config.reviewers[0].name, "my-style");
    }

    #[test]
    fn merge_deduplicates_an_identical_reviewer() {
        // The same reviewer defined in both files collapses to one; no `repo:` scope,
        // since there is nothing to disambiguate.
        let repo = registry_dir(REPO_YAML);
        let user = registry_dir(REPO_YAML);
        let config = Config::discover_merged(repo.path(), Some(user.path())).expect("dedups");
        assert_eq!(config.reviewers.len(), 1);
        assert_eq!(config.reviewers[0].name, "tenant-isolation");
    }

    #[test]
    fn merge_scopes_the_repo_side_on_a_differing_collision() {
        // Same name, different prompt: a genuine collision. Both survive, the user's
        // under the plain name and the repo's scoped to `repo:`.
        let repo = registry_dir(REPO_YAML);
        let user = registry_dir(
            "reviewers:\n  - name: tenant-isolation\n    trigger: [src/**]\n    mode: gate\n    prompt: user prompt\n",
        );
        let config = Config::discover_merged(repo.path(), Some(user.path())).expect("scopes");
        let by_name: std::collections::BTreeMap<&str, &str> = config
            .reviewers
            .iter()
            .map(|r| (r.name.as_str(), r.prompt.as_str()))
            .collect();
        assert_eq!(by_name.get("tenant-isolation"), Some(&"user prompt"));
        assert_eq!(by_name.get("repo:tenant-isolation"), Some(&"repo prompt"));
    }

    #[test]
    fn merge_errors_when_neither_registry_exists() {
        let empty_repo = tempfile::tempdir().unwrap();
        let empty_user = tempfile::tempdir().unwrap();
        let err = Config::discover_merged(empty_repo.path(), Some(empty_user.path())).unwrap_err();
        assert!(err.to_string().contains("no reviewer registry found"));
        // The message points at the user config directory it also searched.
        assert!(
            err.to_string()
                .contains(&empty_user.path().display().to_string())
        );
    }

    #[test]
    fn merge_without_a_user_dir_is_repo_only_discovery() {
        let repo = registry_dir(REPO_YAML);
        let config = Config::discover_merged(repo.path(), None).expect("repo only");
        assert_eq!(config.reviewers.len(), 1);
    }

    #[test]
    fn locate_user_falls_back_to_the_yml_spelling() {
        // Only `.bastion.yml` present: the flat user-config locator still finds it.
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(REGISTRY_FILES[1]), "reviewers: []\n").unwrap();
        assert!(
            locate_user(dir.path())
                .expect("stat ok")
                .expect("located")
                .ends_with(REGISTRY_FILES[1])
        );
    }

    #[test]
    fn a_present_but_unloadable_user_registry_fails_closed() {
        // `.bastion.yaml` exists in the user config dir but as a directory, not a
        // loadable file. Discovery must not read that as "no user registry" and
        // silently drop the user's gate reviewers; it returns the path and the load
        // fails closed with a clear error.
        let user = tempfile::tempdir().unwrap();
        std::fs::create_dir(user.path().join(REGISTRY_FILE)).unwrap();
        let repo = registry_dir(REPO_YAML);
        let err = Config::discover_merged(repo.path(), Some(user.path())).unwrap_err();
        assert!(
            format!("{err:#}").contains("reviewer registry"),
            "a present-but-unloadable user registry must error, got: {err:#}"
        );
    }

    #[test]
    fn the_shipped_registry_loads_and_is_well_formed() {
        // The registry under bastion/ is load-bearing: it is what Bastion uses to
        // review its own changes locally and in CI. Guard it so an edit that makes
        // it unparseable, duplicates a name, or leaves a reviewer empty fails here
        // rather than at review time.
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(REGISTRY_FILE);
        let config = Config::load(&path).expect("shipped .bastion.yaml loads");

        assert!(
            !config.reviewers.is_empty(),
            "the shipped registry should define reviewers"
        );
        for reviewer in &config.reviewers {
            assert!(!reviewer.name.is_empty(), "reviewer name must be non-empty");
            assert!(
                !reviewer.trigger.is_empty(),
                "reviewer '{}' must declare at least one trigger glob",
                reviewer.name
            );
            assert!(
                !reviewer.prompt.trim().is_empty(),
                "reviewer '{}' must carry a prompt",
                reviewer.name
            );
        }
    }
}
