//! Loading the reviewer registry from disk.
//!
//! Reviewers are declarative and static, defined in a `.bastion.yaml` (or
//! `.bastion.yml`) file at the repository root, under a `reviewers:` key. Keeping
//! them on disk (not generated by code) is what makes them reviewable and gives a
//! stable trigger set.

use std::path::{Path, PathBuf};

use color_eyre::eyre::{Context, Result, bail, eyre};
use serde::{Deserialize, Serialize};

use crate::reviewer::Reviewer;

/// The canonical registry file name at the repository root.
pub const REGISTRY_FILE: &str = ".bastion.yaml";

/// The registry file names discovery accepts, in precedence order. Both the
/// `.yaml` and `.yml` spellings are honored; if both exist in the same directory,
/// `.bastion.yaml` wins.
pub const REGISTRY_FILES: [&str; 2] = [".bastion.yaml", ".bastion.yml"];

/// The deprecated pre-rename registry location (`bastion/reviewers.yaml`),
/// relative to the repository root.
///
/// Discovery still finds it, with the lowest precedence, so existing repositories
/// keep working: a directory's `.bastion.yaml`/`.bastion.yml` wins over this, and a
/// closer ancestor wins over a farther one. When it is the file that resolves,
/// [`Config::discover`] logs a deprecation warning pointing at [`REGISTRY_FILE`].
/// This shim will be removed in a future release.
pub const LEGACY_REGISTRY_RELPATH: &str = "bastion/reviewers.yaml";

/// The parsed reviewer registry.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Config {
    /// The reviewers defined for this repository.
    #[serde(default)]
    pub reviewers: Vec<Reviewer>,
}

impl Config {
    /// Parse a registry from YAML text, validating reviewer-name uniqueness.
    ///
    /// # Errors
    ///
    /// Returns an error if the YAML is malformed or two reviewers share a name.
    pub fn from_yaml(yaml: &str) -> Result<Self> {
        let config: Config =
            serde_yaml_ng::from_str(yaml).wrap_err("reviewer registry is not valid YAML")?;
        config.validate()?;
        Ok(config)
    }

    /// Load and parse the registry at `path`.
    ///
    /// # Errors
    ///
    /// Returns an error if the file cannot be read or fails [`Config::from_yaml`].
    pub fn load(path: &Path) -> Result<Self> {
        let yaml = std::fs::read_to_string(path)
            .wrap_err_with(|| format!("reading reviewer registry at {}", path.display()))?;
        Self::from_yaml(&yaml)
            .wrap_err_with(|| format!("parsing reviewer registry at {}", path.display()))
    }

    /// Discover and load the registry by walking up from `start` looking for a
    /// `.bastion.yaml` (or `.bastion.yml`) at each ancestor directory.
    ///
    /// Falls back to the deprecated [`LEGACY_REGISTRY_RELPATH`] location, logging a
    /// deprecation warning when that is what resolves.
    ///
    /// # Errors
    ///
    /// Returns an error if no registry is found in any ancestor directory, or if
    /// the discovered file fails to load.
    pub fn discover(start: &Path) -> Result<Self> {
        let found = locate_kind(start).ok_or_else(|| {
            eyre!(
                "no reviewer registry found; expected {} (or {}) in this repo or an ancestor",
                REGISTRY_FILES[0],
                REGISTRY_FILES[1],
            )
        })?;
        if found.deprecated {
            tracing::warn!(
                "reviewer registry found at the deprecated path `{}`; rename it to `{}` at the repository root. The old location still works for now but will stop being read in a future release.",
                LEGACY_REGISTRY_RELPATH,
                REGISTRY_FILE,
            );
        }
        Self::load(&found.path)
    }

    fn validate(&self) -> Result<()> {
        let mut seen = std::collections::BTreeSet::new();
        for reviewer in &self.reviewers {
            if !seen.insert(reviewer.name.as_str()) {
                bail!("duplicate reviewer name: {}", reviewer.name);
            }
        }
        Ok(())
    }
}

/// A located registry file and whether it came from the deprecated location.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Found {
    /// The resolved path to the registry file.
    pub path: PathBuf,
    /// True when `path` is the deprecated [`LEGACY_REGISTRY_RELPATH`] location.
    pub deprecated: bool,
}

/// Locate the registry file by walking up from `start`.
///
/// Returns the path to the first registry found in an ancestor directory, or
/// `None` if none exists up to the filesystem root. Within a single directory the
/// `.bastion.yaml` spelling wins over `.bastion.yml`, and both win over the
/// deprecated `bastion/reviewers.yaml`; a closer ancestor wins over a farther one.
#[must_use]
pub fn locate(start: &Path) -> Option<PathBuf> {
    locate_kind(start).map(|found| found.path)
}

/// Like [`locate`], but also reports whether the resolved path is the deprecated
/// location, so callers can warn.
#[must_use]
pub fn locate_kind(start: &Path) -> Option<Found> {
    for dir in start.ancestors() {
        for name in REGISTRY_FILES {
            let candidate = dir.join(name);
            if candidate.is_file() {
                return Some(Found {
                    path: candidate,
                    deprecated: false,
                });
            }
        }
        let legacy = dir.join(LEGACY_REGISTRY_RELPATH);
        if legacy.is_file() {
            return Some(Found {
                path: legacy,
                deprecated: true,
            });
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_a_two_reviewer_registry() {
        let yaml = r"
reviewers:
  - name: file-responsibility
    trigger: [src/**/*.ts]
    mode: gate
    prompt: Check single responsibility.
  - name: api-compatibility
    trigger: [src/server/**, src/client/**]
    mode: gate
    prompt: Check API compatibility.
";
        let config = Config::from_yaml(yaml).expect("valid registry");
        assert_eq!(config.reviewers.len(), 2);
        assert_eq!(config.reviewers[0].name, "file-responsibility");
    }

    #[test]
    fn rejects_duplicate_reviewer_names() {
        let yaml = r"
reviewers:
  - name: dup
    trigger: [a]
    mode: gate
    prompt: one
  - name: dup
    trigger: [b]
    mode: advisor
    prompt: two
";
        let err = Config::from_yaml(yaml).unwrap_err();
        assert!(err.to_string().contains("duplicate reviewer name"));
    }

    #[test]
    fn discovers_registry_in_an_ancestor_directory() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILE),
            "reviewers:\n  - name: r\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let nested = tmp.path().join("src").join("deep");
        std::fs::create_dir_all(&nested).unwrap();

        let config = Config::discover(&nested).expect("found via ancestor walk");
        assert_eq!(config.reviewers.len(), 1);
    }

    #[test]
    fn discovers_the_yml_spelling_too() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILES[1]),
            "reviewers:\n  - name: r\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let config = Config::discover(tmp.path()).expect("found via .yml spelling");
        assert_eq!(config.reviewers.len(), 1);
    }

    #[test]
    fn the_yaml_spelling_wins_when_both_exist() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILES[0]),
            "reviewers:\n  - name: from-yaml\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILES[1]),
            "reviewers:\n  - name: from-yml\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let config = Config::discover(tmp.path()).expect("found, .yaml wins");
        assert_eq!(config.reviewers[0].name, "from-yaml");
    }

    #[test]
    fn discovers_the_deprecated_legacy_location() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join("bastion")).unwrap();
        std::fs::write(
            tmp.path().join(LEGACY_REGISTRY_RELPATH),
            "reviewers:\n  - name: legacy\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        // It resolves and loads.
        let config = Config::discover(tmp.path()).expect("legacy registry still discovered");
        assert_eq!(config.reviewers[0].name, "legacy");

        // ...and it is flagged as deprecated so the caller can warn.
        let found = locate_kind(tmp.path()).expect("legacy located");
        assert!(found.deprecated, "legacy path must be flagged deprecated");
        assert!(found.path.ends_with("reviewers.yaml"));
    }

    #[test]
    fn the_root_registry_wins_over_the_legacy_location() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(REGISTRY_FILE),
            "reviewers:\n  - name: from-root\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();
        std::fs::create_dir_all(tmp.path().join("bastion")).unwrap();
        std::fs::write(
            tmp.path().join(LEGACY_REGISTRY_RELPATH),
            "reviewers:\n  - name: from-legacy\n    trigger: [x]\n    mode: gate\n    prompt: p\n",
        )
        .unwrap();

        let found = locate_kind(tmp.path()).expect("located");
        assert!(
            !found.deprecated,
            "the root .bastion.yaml must win over the legacy path"
        );
        let config = Config::discover(tmp.path()).expect("loads the root registry");
        assert_eq!(config.reviewers[0].name, "from-root");
    }

    #[test]
    fn discovery_fails_clearly_when_absent() {
        let tmp = tempfile::tempdir().unwrap();
        let err = Config::discover(tmp.path()).unwrap_err();
        assert!(err.to_string().contains("no reviewer registry found"));
    }

    #[test]
    fn the_shipped_registry_loads_and_is_well_formed() {
        // The registry under bastion/ is load-bearing: it is what Bastion uses to
        // review its own changes locally and in CI. Guard it so an edit that makes
        // it unparseable, duplicates a name, or leaves a reviewer empty fails here
        // rather than at review time.
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(REGISTRY_FILE);
        let config = Config::load(&path).expect("shipped .bastion.yaml loads");

        assert!(
            !config.reviewers.is_empty(),
            "the shipped registry should define reviewers"
        );
        for reviewer in &config.reviewers {
            assert!(!reviewer.name.is_empty(), "reviewer name must be non-empty");
            assert!(
                !reviewer.trigger.is_empty(),
                "reviewer '{}' must declare at least one trigger glob",
                reviewer.name
            );
            assert!(
                !reviewer.prompt.trim().is_empty(),
                "reviewer '{}' must carry a prompt",
                reviewer.name
            );
        }
    }

    #[test]
    fn unprovisioned_capabilities_gate_guards_the_registry() {
        // The unprovisioned-capabilities reviewer is the authoring-time guard
        // against a reviewer declaring a capability this build cannot provision.
        // Pin its routing so a typo in its trigger or a flip from gate to advisor
        // fails here rather than silently disarming the guard.
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(REGISTRY_FILE);
        let config = Config::load(&path).expect("shipped registry loads");
        let gate = config
            .reviewers
            .iter()
            .find(|r| r.name == "unprovisioned-capabilities")
            .expect("the unprovisioned-capabilities reviewer is present");
        assert_eq!(
            gate.mode,
            crate::reviewer::Mode::Gate,
            "unprovisioned-capabilities must be a gate, not an advisor"
        );
        assert!(
            gate.trigger.iter().any(|t| t == ".bastion.yaml"),
            "unprovisioned-capabilities must trigger on the registry it guards (got {:?})",
            gate.trigger
        );
        // Pin the policy clauses the container-runner work changed, so a prompt edit
        // that silently re-broadened the guard (back to blocking a `runner`, or
        // forward to letting `mcp`/`skills` through) fails here. The runner block is
        // now provisioned, a native `network: true` still fails closed, and `mcp` and
        // `skills` remain unprovisioned.
        let prompt = &gate.prompt;
        assert!(
            prompt.contains("the container `runner` block"),
            "the gate prompt must state the `runner` block is provisioned"
        );
        assert!(
            prompt.contains("does NOT yet provision the `mcp` or `skills`"),
            "the gate prompt must still treat `mcp` and `skills` as unprovisioned"
        );
        assert!(
            prompt.contains("NO `runner` block"),
            "the gate prompt must still block native `network: true` (no `runner`)"
        );
    }
}
