//! The agent skills Bastion bundles into the binary and installs into a
//! consuming repository.
//!
//! These teach a coding agent how to *use* Bastion: drive the local
//! `bastion review` loop, read the streamed findings, and reach a green gate
//! before opening a PR. They are distinct from the repo-local Rust skills under
//! `.agents/skills/` in this repository, which teach agents working *on* Bastion.
//!
//! Each skill's source lives under `skills/<slug>/SKILL.md` and is embedded at
//! build time, so `bastion skills install` is self-contained and offline. The
//! command writes one copy per target directory (Claude Code's `.claude/skills`
//! and the agent-neutral `.agents/skills`), so [`check`] can flag a checked-in
//! copy that has drifted from the binary's embedded source, whether by a hand
//! edit or a stale install left behind when the source changed. The rendered file
//! is deterministic and version-independent, so it stays byte-stable across
//! bastion upgrades that do not touch the skill text: that is what lets `check`
//! serve as a CI drift guard rather than going red on every release.

use std::fs;
use std::path::{Path, PathBuf};

use color_eyre::eyre::{Context, Result};

/// The marker line a bundled skill carries just below its front matter.
/// [`BundledSkill::render`] replaces it with a static provenance comment marking
/// the file as generated.
const PROVENANCE_MARKER: &str = "<!-- BASTION_SKILL_PROVENANCE -->";

/// The provenance comment [`BundledSkill::render`] writes in place of the marker.
/// It carries no version, so the rendered file is identical across bastion builds
/// (see the module docs on why `check` must be version-independent).
const PROVENANCE: &str = "<!-- Generated by `bastion skills install`. Do not edit by hand; \
re-run `bastion skills install` to refresh it from the installed binary. -->";

/// The directories `bastion skills install` writes into by default, relative to
/// the repository root. `.claude/skills` is Claude Code's native discovery path;
/// `.agents/skills` is the agent-neutral convention Bastion itself follows.
pub const DEFAULT_DIRS: &[&str] = &[".claude/skills", ".agents/skills"];

/// Every skill compiled into this binary.
pub const BUNDLED: &[BundledSkill] = &[BundledSkill {
    slug: "using-bastion",
    summary: "How an agent drives the local bastion review loop to a green gate.",
    source: include_str!("../skills/using-bastion/SKILL.md"),
}];

/// A skill compiled into the binary, installable into a consuming repository.
pub struct BundledSkill {
    /// The directory name under each skills root, and the skill's `name`.
    pub slug: &'static str,
    /// A one-line summary for `bastion skills list`.
    pub summary: &'static str,
    /// The raw `SKILL.md` source, carrying the [`PROVENANCE_MARKER`].
    source: &'static str,
}

/// Normalize line endings to LF.
///
/// The bundled `SKILL.md` is embedded with `include_str!`, so its bytes are
/// whatever git checked out: on Windows with `core.autocrlf`, that is CRLF. The
/// rendered file must be byte-identical on every platform, because [`check`]
/// compares a checked-in copy against [`BundledSkill::render`] byte for byte and
/// fails closed on any difference. The `.gitattributes` entry forcing LF on the
/// skill assets is the first line of defense; normalizing here keeps the binary
/// correct even when it is built from a source checkout that slipped through with
/// CRLF (for example an unpacked tarball).
fn normalize_newlines(source: &str) -> String {
    source.replace("\r\n", "\n")
}

impl BundledSkill {
    /// The skill file as it should appear on disk, with the provenance marker
    /// replaced by the [`PROVENANCE`] comment. Line endings are normalized to LF
    /// so the output is deterministic, version-independent, and identical on every
    /// platform: a checked-in copy stays byte-stable across bastion upgrades that
    /// do not change the skill text. That is precisely what lets [`check`] run as a
    /// CI drift guard without going red on every release or on Windows checkouts.
    #[must_use]
    pub fn render(&self) -> String {
        normalize_newlines(self.source).replace(PROVENANCE_MARKER, PROVENANCE)
    }

    /// This skill's path under one skills root: `<dir>/<slug>/SKILL.md`.
    fn path_in(&self, dir: &Path) -> PathBuf {
        dir.join(self.slug).join("SKILL.md")
    }
}

/// The [`DEFAULT_DIRS`] as owned, repo-relative paths.
#[must_use]
pub fn default_dirs() -> Vec<PathBuf> {
    DEFAULT_DIRS.iter().map(PathBuf::from).collect()
}

/// What installing one skill file did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Installed {
    /// The file did not exist and was written.
    Created,
    /// The file existed with different content and was overwritten (`--force`).
    Updated,
    /// The file already matched what we would write; nothing was touched.
    Unchanged,
    /// The file existed with different content and `--force` was not set, so it
    /// was left untouched.
    Skipped,
}

/// The result of installing one skill into one directory.
pub struct InstallOutcome {
    /// Where the skill file lives.
    pub path: PathBuf,
    /// What happened to it.
    pub status: Installed,
}

/// Write every bundled skill into each of `dirs` (resolved against `root`).
///
/// An existing file that already matches is left as [`Installed::Unchanged`]. One
/// that differs is overwritten only when `force` is set; otherwise it is reported
/// as [`Installed::Skipped`] and left exactly as it was, so a local edit is never
/// clobbered silently.
///
/// # Errors
///
/// Returns an error if a directory cannot be created or a file cannot be read or
/// written.
pub fn install(root: &Path, dirs: &[PathBuf], force: bool) -> Result<Vec<InstallOutcome>> {
    let mut outcomes = Vec::new();
    for skill in BUNDLED {
        let rendered = skill.render();
        for dir in dirs {
            let path = skill.path_in(&root.join(dir));
            let status = install_one(&path, &rendered, force)?;
            outcomes.push(InstallOutcome { path, status });
        }
    }
    Ok(outcomes)
}

/// Install one rendered skill file, returning what it did.
fn install_one(path: &Path, rendered: &str, force: bool) -> Result<Installed> {
    // Compare on normalized newlines: a consuming repo's `core.autocrlf` can hand
    // back a CRLF copy of a file we wrote as LF, and that is the same skill, not an
    // edit. `rendered` is already LF (see [`BundledSkill::render`]).
    let status = match read_if_exists(path)? {
        Some(current) if normalize_newlines(&current) == rendered => Installed::Unchanged,
        Some(_) if !force => Installed::Skipped,
        Some(_) => Installed::Updated,
        None => Installed::Created,
    };
    if matches!(status, Installed::Created | Installed::Updated) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .wrap_err_with(|| format!("creating skill directory {}", parent.display()))?;
        }
        fs::write(path, rendered)
            .wrap_err_with(|| format!("writing skill file {}", path.display()))?;
    }
    Ok(status)
}

/// Whether one installed skill file matches what this binary would write.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Checked {
    /// Present and byte-identical to the rendered skill.
    UpToDate,
    /// Present but different: hand-edited, or a stale install left behind when the
    /// skill source changed.
    Drifted,
    /// Not installed at all.
    Missing,
}

/// The result of checking one skill in one directory.
pub struct CheckOutcome {
    /// Where the skill file would live.
    pub path: PathBuf,
    /// How it compares to what this binary would write.
    pub status: Checked,
}

/// Compare every bundled skill in each of `dirs` (resolved against `root`)
/// against what this binary would write, without changing anything.
///
/// This is the read-only mirror of [`install`]: a CI step can run it to fail when
/// the checked-in skills have drifted from the binary's embedded source.
///
/// # Errors
///
/// Returns an error if a skill file exists but cannot be read.
pub fn check(root: &Path, dirs: &[PathBuf]) -> Result<Vec<CheckOutcome>> {
    let mut outcomes = Vec::new();
    for skill in BUNDLED {
        let rendered = skill.render();
        for dir in dirs {
            let path = skill.path_in(&root.join(dir));
            // Normalize newlines before comparing: a consuming repo's
            // `core.autocrlf` may check our LF file back out as CRLF, which is the
            // same content, not drift. Only a genuine content edit counts.
            let status = match read_if_exists(&path)? {
                Some(current) if normalize_newlines(&current) == rendered => Checked::UpToDate,
                Some(_) => Checked::Drifted,
                None => Checked::Missing,
            };
            outcomes.push(CheckOutcome { path, status });
        }
    }
    Ok(outcomes)
}

/// Read a file to a string, mapping a missing file to `None` rather than an error.
fn read_if_exists(path: &Path) -> Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(content) => Ok(Some(content)),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(err).wrap_err_with(|| format!("reading {}", path.display())),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_skill_is_a_valid_skill_file() {
        // Every bundled skill must be a Claude Code skill: front matter first, with
        // a name matching its slug so the installed directory and the skill agree.
        // Normalize newlines first: the embedded source carries CRLF on a Windows
        // checkout, but the skill is identical content on every platform.
        for skill in BUNDLED {
            let source = normalize_newlines(skill.source);
            assert!(
                source.starts_with("---\n"),
                "{} must start with YAML front matter",
                skill.slug
            );
            assert!(
                source.contains(&format!("name: {}", skill.slug)),
                "{} front matter must declare its slug as `name`",
                skill.slug
            );
            assert!(
                source.contains(PROVENANCE_MARKER),
                "{} must carry the provenance marker so install can stamp it",
                skill.slug
            );
        }
    }

    #[test]
    fn render_drops_the_marker_for_a_static_provenance_comment() {
        let out = BUNDLED[0].render();
        assert!(
            !out.contains(PROVENANCE_MARKER),
            "marker should be replaced"
        );
        assert!(
            out.contains("Generated by `bastion skills install`"),
            "provenance comment should be present"
        );
        assert!(out.starts_with("---\n"), "front matter must remain first");
        // Render must be deterministic: no version or other volatile data leaks in,
        // so a checked-in copy stays byte-stable across builds (the CI guard relies
        // on this).
        assert_eq!(out, BUNDLED[0].render());
    }

    #[test]
    fn render_is_lf_only_on_every_platform() {
        // The drift guard compares byte for byte, so the rendered file must use LF
        // regardless of how git checked out the embedded source (CRLF on Windows).
        for skill in BUNDLED {
            assert!(
                !skill.render().contains('\r'),
                "{} render must not carry CR; it would drift against a LF checkout",
                skill.slug
            );
        }
    }

    #[test]
    fn install_creates_then_is_idempotent_then_force_overwrites_edits() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        let expected = BUNDLED.len() * DEFAULT_DIRS.len();

        let first = install(root, &default_dirs(), false).unwrap();
        assert_eq!(first.len(), expected);
        assert!(first.iter().all(|o| o.status == Installed::Created));
        assert!(root.join(".claude/skills/using-bastion/SKILL.md").exists());
        assert!(root.join(".agents/skills/using-bastion/SKILL.md").exists());

        // Re-running changes nothing: the render is deterministic.
        let again = install(root, &default_dirs(), false).unwrap();
        assert!(again.iter().all(|o| o.status == Installed::Unchanged));

        // A local edit is left alone without --force...
        let edited = root.join(".claude/skills/using-bastion/SKILL.md");
        fs::write(&edited, "hand edited\n").unwrap();
        let skipped = install(root, &default_dirs(), false).unwrap();
        let edited_status = skipped.iter().find(|o| o.path == edited).unwrap().status;
        assert_eq!(edited_status, Installed::Skipped);
        assert_eq!(fs::read_to_string(&edited).unwrap(), "hand edited\n");

        // ...and overwritten with --force.
        let forced = install(root, &default_dirs(), true).unwrap();
        let forced_status = forced.iter().find(|o| o.path == edited).unwrap().status;
        assert_eq!(forced_status, Installed::Updated);
        assert_eq!(fs::read_to_string(&edited).unwrap(), BUNDLED[0].render());
    }

    #[test]
    fn check_reports_missing_then_uptodate_then_drift() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();

        let missing = check(root, &default_dirs()).unwrap();
        assert!(missing.iter().all(|o| o.status == Checked::Missing));

        install(root, &default_dirs(), false).unwrap();
        let ok = check(root, &default_dirs()).unwrap();
        assert!(ok.iter().all(|o| o.status == Checked::UpToDate));

        // A hand edit shows as drift; the untouched sibling stays up to date.
        let edited = root.join(".claude/skills/using-bastion/SKILL.md");
        fs::write(&edited, "tampered\n").unwrap();
        let after = check(root, &default_dirs()).unwrap();
        let edited_status = after.iter().find(|o| o.path == edited).unwrap().status;
        assert_eq!(edited_status, Checked::Drifted);
        assert!(
            after
                .iter()
                .any(|o| o.path != edited && o.status == Checked::UpToDate)
        );
    }

    #[test]
    fn crlf_checkout_is_not_drift_but_a_real_edit_is() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        install(root, &default_dirs(), false).unwrap();

        // A consuming repo's autocrlf can rewrite our LF file as CRLF on checkout.
        // That is the same skill, so check must stay green and install idempotent.
        let file = root.join(".claude/skills/using-bastion/SKILL.md");
        let crlf = BUNDLED[0].render().replace('\n', "\r\n");
        fs::write(&file, &crlf).unwrap();

        let checked = check(root, &default_dirs()).unwrap();
        let status = checked.iter().find(|o| o.path == file).unwrap().status;
        assert_eq!(
            status,
            Checked::UpToDate,
            "CRLF newlines must not read as drift"
        );

        let reinstall = install(root, &default_dirs(), false).unwrap();
        let install_status = reinstall.iter().find(|o| o.path == file).unwrap().status;
        assert_eq!(
            install_status,
            Installed::Unchanged,
            "a CRLF copy of the same content needs no rewrite"
        );

        // A genuine content edit still drifts, CRLF endings notwithstanding.
        fs::write(&file, "tampered\r\n").unwrap();
        let after = check(root, &default_dirs()).unwrap();
        let drifted = after.iter().find(|o| o.path == file).unwrap().status;
        assert_eq!(drifted, Checked::Drifted, "a real edit must still drift");
    }
}
